version: "3"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.17.6
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  logstash:
    container_name: logstash-container
    image: docker.elastic.co/logstash/logstash:7.17.6
    volumes:
      - "./logstash.conf:/config-dir/logstash.conf"
    # restart: always
    entrypoint: ["/bin/sh", "-c"]
    ports:
      - "9600:9600"
      - "7777:7777"
    depends_on:
      - elasticsearch
    command: |
      "
      echo -e 'Creating installing logstash-output-mongodb :'
      bin/logstash-plugin install --version=3.1.5 logstash-output-mongodb
      logstash -f /config-dir/logstash.conf
      "

networks:
  default:
    name: kafka-network
    external: true
volumes:
  elasticsearch:
    driver: local
