version: "3"

services:
  backend:
    build: ./Backend
    container_name: backend
    ports:
      - 80:80
    # env_file:
    #   - ./Backend/.env
    volumes:
      - ./Backend:/app

networks:
  default:
    name: kafka-network
    external: true
