version: "3"

services:
  backend:
    build: ./Backend
    ports:
      - 80:80
    # env_file:
    #   - ./Backend/.env
    volumes:
      - ./Backend:/app
  frontend:
    build: ./Frontend
    ports:
      - 8888:5173
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL=localhost:80
      VITE_MINIO_URL=localhost:9000
networks:
  default:
    name: kafka-network
    external: true
